class NativeBrowser:
    def __init__(self, options_json: str | None = None) -> None: ...
    def execute_json(self, command_json: str) -> str: ...

def browser_cache_dir() -> str: ...
def find_chrome_executable() -> str | None: ...
def _run_browser_install(with_deps: bool = False) -> None: ...
def skill_data_json() -> str: ...

__agent_browser_version__: str
