class NativeBrowser:
    def __init__(self, options_json: str | None = None) -> None: ...
    def execute_json(self, command_json: str) -> str: ...

def skill_data_json() -> str: ...

__agent_browser_version__: str
